### ISSUE TITLE
LibreSSL support?

### ISSUE THREAD

**Issue by Mikaela** [jimloco/Csocket#47]
> libressl works, but it needs an extra header to be included in csocket or it won't compile

via https://github.com/znc/znc/pull/894#issuecomment-76180851

I am still unsure if it would break anything else as can be seen from that discussion, but it probably wouldn't hurt if it was supported (and didn't break anything). At least OS X has libressl in homebrew.

**Comment by Sp1l** [comment]
Check https://github.com/jimloco/Csocket/pull/49

**Comment by Mikaela** [comment]
Could you upgrade description of #49 to includes "Closes #47"? That should automatically close this issue when it gets merged.

**Comment by Sp1l** [comment]
Like so?

**Comment by Mikaela** [comment]
Just adding it to the end should work

**Comment by Sp1l** [comment]
Ah, like so! :D

**Comment by Mikaela** [comment]
Yes, that is what I meant :)

**Comment by brad0** [comment]
There is still a piece missing as mentioned in this ZNC ticket.. https://github.com/znc/znc/issues/594.

http://openbsd.comstyle.com/cgi/cvsweb/ports/net/znc/patches/patch-src_Csocket_cpp?rev=1.1&content-type=text/x-cvsweb-markup

**Comment by Mikaela** [comment]
I guess @Sp1l could also add "closes "znc/znc#594" to description of #49 so it would automatically get closes when ZNC updates the submodule to version including it.

**Comment by Sp1l** [comment]
"Your wish was granted"
