### ISSUE TITLE
Question: Should Csocket (on Unix) support Unix sockets?

### ISSUE THREAD

**Issue by psychon** [jimloco/Csocket#68]
Hi,

there is a [feature request](https://github.com/znc/znc/issues/1240) asking that ZNC should support listening on Unix sockets. [The question now](https://github.com/znc/znc/pull/1363#issuecomment-272552651) is if this should be done in Csocket or only in ZNC. I guess on Windows, the API would just not be available.
What do you think about this? Should I implement the low-level bits of this in Csocket or in ZNC?

**Comment by jimloco** [comment]
Csocket is a pretty good location for it IMHO.
